export enum CollectionName {
  companies = 'Companies',
  companyBranch = 'CompanyBranch',
  admins = 'Admins',
  employeeRoles = 'EmployeeRoles',
  employees = 'Employees',
  shifts = 'Shifts',
  patrols = 'Patrols',
  patrolLogs = 'PatrolLogs',
  messages = 'Messages',
  loggedInUsers = 'LoggedInUsers',
  locations = 'Locations',
  reportCategories = 'ReportCategories',
  reports = 'Reports',
  invoices = 'Invoices',
  clients = 'Clients',
  documentCategories = 'DocumentCategories',
  documents = 'Documents',
  settings = 'Settings',
  superAdmin = 'SuperAdmin',
  equipments = 'Equipments',
  equipmentAllocations = 'EquipmentAllocations',
  employeesDAR = 'EmployeesDAR',
  visitors = 'Visitors',
  keys = 'Keys',
  keyAllocations = 'KeyAllocations',
  tasks = 'Tasks',
  taskLogs = 'TaskLogs',
  employeeRoutes = 'EmployeeRoutes',
  shiftExchangeRequests = 'ShiftExchangeRequests',
  callouts = 'Callouts',
  userDataDeletionRequests = 'UserDataDeletionRequests',
  payStubs = 'PayStubs',
  trainingAndCertifications = 'TrainingAndCertifications',
  trainCertsAllocation = 'TrainCertsAllocation',
  emergencyProtocols = 'EmergencyProtocols',
  leaveRequests = 'LeaveRequests',
}

export const DisplayCount = {
  EMPLOYEE_LIST: 20,
  SHIFT_LIST: 20,
  PATROL_LIST: 20,
  PATROL_LOG_LIST: 20,
  LOCATION_LIST: 20,
  REPORT_LIST: 20,
  INVOICE_LIST: 20,
  CLIENT_LIST: 20,
  DOCUMENT_LIST: 20,
  EQUIPMENT_LIST: 20,
  EQUIPMENT_ALLOCATION_LIST: 20,
  MESSAGE_RECEIVED_LIST: 20,
  MESSAGE_SENT_LIST: 20,
  EMP_DAR_LIST: 20,
  VISITOR_LIST: 20,
  KEY_LIST: 20,
  KEY_ALLOCATION: 20,
  TASK_LIST: 20,
  TASK_LOG_LIST: 20,
  CALLOUT_LIST: 20,
  PAY_STUB_LIST: 20,
  COMPANY_LIST: 20,
  TRAIN_CERTS_LIST: 20,
  TRAIN_CERTS_ALLOC_LIST: 20,
  EMERG_PROTOCOLS_LIST: 20,
} as const;

export const REACT_QUERY_KEYS = {
  EMPLOYEE_LIST: 'employee-list',
  SHIFT_LIST: 'shift-list',
  SCHEDULES: 'schedules',
  PATROL_LIST: 'patrolling-list',
  PATROL_LOG_LIST: 'patrol-log-list',
  LOCATION_LIST: 'location-list',
  REPORT_LIST: 'report-list',
  REPORT_CATEGORIES: 'report-categories',
  INVOICE_LIST: 'invoice-list',
  CLIENT_LIST: 'client-list',
  DOCUMENT_LIST: 'document-list',
  DOCUMENT_CATEGORIES: 'document-categories',
  EQUIPMENT_LIST: 'equipment-list',
  EQUIPMENT_ALLOCATION_LIST: 'equipment-allocation-list',
  MESSAGE_RECEIVED_LIST: 'message-received-list',
  MESSAGE_SENT_LIST: 'message-sent-list',
  EMP_DAR_LIST: 'emp-dar-list',
  VISITOR_LIST: 'visitor-list',
  KEY_LIST: 'key-list',
  KEY_ALLOCATION: 'key-allocation',
  TASK_LIST: 'task-list',
  TASK_LOG_LIST: 'task-log-list',
  CALLOUT_LIST: 'callout-list',
  PAY_STUB_LIST: 'pay-stub-list',
  COMPANY_LIST: 'company-list',
  TRAIN_CERTS_LIST: 'train-certs-list',
  TRAIN_CERTS_ALLOC_LIST: 'train-certs-alloc-list',
  EMERG_PROTOCOLS_LIST: 'emerg-protocol-list',
} as const;

export const MinimumQueryCharacter = {
  EMPLOYEE: 1,
  PATROL: 1,
  LOCATION: 1,
  CLIENT: 1,
  DOCUMENT: 1,
  EQUIPMENT: 1,
  EMP_DAR: 1,
  KEY: 1,
  TASK_LIST: 1,
  PAY_STUB: 1,
  COMPANY: 1,
  TRAIN_CERTS: 1,
  EMERG_PROTOCOLS: 1,
} as const;

export const CloudStoragePaths = {
  EMPLOYEES_IMAGES: 'employees/images/',
  EMPLOYEES_DOCUMENTS: 'employees/documents',
  COMPANIES_LOGOS: 'companies/logos',
  DOCUMENTS: 'documents',
  CLIENT_IMAGES: 'clients/images',
  CLIENT_DOCUMENTS: 'clients/documents',
  COMPANIES_LOCATIONS_DOCUMENTS: 'companies/locations/documents',
  COMPANIES_EMERGENCY_PROTOCOLS: 'companies/emergency_protocols',
};

export const ImageResolution = {
  EMP_IMAGE_WIDTH: 720,
  EMP_IMAGE_HEIGHT: 720,
  EMP_LICENSE_WIDTH: 480,
  EMP_LICENSE_HEIGHT: 480,
  EMP_VOID_CHECK_WIDTH: 720,
  EMP_VOID_CHECK_HEIGHT: 480,
  COMPANY_LOGO_WIDTH: 1200,
  COMPANY_LOGO_HEIGHT: 1200,
  CLIENT_HOME_PAGE_BG_IMG_WIDTH: 1200,
  CLIENT_HOME_PAGE_BG_IMG_HEIGHT: 700,
};

export const PageRoutes = {
  HOME: '/',
  SHIFT_LIST: '/shift_list',
  SHIFT_VIEW: '/shift_view',
  SHIFT_CREATE_OR_EDIT: '/shift_create_or_edit',
  EMPLOYEE_ROUTE: '/employee_route',
  EMPLOYEE_LIST: '/employee_list',
  EMPLOYEE_CREATE_OR_EDIT: '/employee_create_or_edit',
  EMPLOYEE_DAR_LIST: '/employee_dar_list',
  EMPLOYEE_DAR_VIEW: '/employee_dar_view',
  SCHEDULES: '/schedules',
  PATROLLING_LIST: '/patrolling_list',
  PATROLLING_LOGS: '/patrolling_logs',
  PATROLLING_CREATE_OR_EDIT: '/patrolling_create_or_edit',
  PATROLLING_VIEW: '/patrolling_view',
  VISITOR_LIST: '/visitor_list',
  VISITOR_VIEW: '/visitor_view',
  LOCATIONS: '/locations',
  LOCATION_CREATE_OR_EDIT: '/location_create_or_edit',
  COMPANY_BRANCHES: '/company_branches',
  REPORTS: '/reports',
  REPORT_VIEW: '/report_view',
  SETTINGS: '/settings',
  PAYMENTS_AND_BILLING: '/payments_and_billing',
  INVOICE_LIST: '/invoice_list',
  INVOICE_GENERATE: '/invoice_generate',
  PAY_STUB_LIST: '/paystub_list',
  PAY_STUB_GENERATE: '/paystub_generate',
  CLIENTS: '/clients',
  CLIENT_VIEW: '/client_view',
  CLIENT_CREATE_OR_EDIT: '/client_create_or_edit',
  SUPER_ADMIN_COMPANY_LIST: '/super_admin/company_list',
  SUPER_ADMIN_CREATE_NEW_COMPANY: '/super_admin/create_new_company',
  DOCUMENT_REPOSITORY: '/document_repository',
  EQUIPMENT_LIST: '/equipment_list',
  EQUIPMENT_VIEW: '/equipment_view',
  KEY_LIST: '/key_list',
  KEY_VIEW: '/key_view',
  MESSAGING: '/messaging',
  TRAINING_AND_CERTIFICATION_LIST: '/training_and_certification_list',
  TRAINING_AND_CERTIFICATION_CREATE_OR_EDIT:
    '/training_and_certification_create_or_edit',
  TRAINING_AND_CERTIFICATION_VIEW: '/training_and_certification_view',
  TIME_AND_ATTENDANCE_LIST: '/time_and_attendance_list',
  TIME_AND_ATTENDANCE_VIEW: '/time_and_attendance_view',
  PERFORMANCE_ASSURANCE: '/performance_assurance',
  TASK_AND_TRACKING_LIST: '/task_and_tracking_list',
  TASK_AND_TRACKING_LOGS: '/task_and_tracking_logs',
  CLIENT_PORTAL_HOME: '/client_portal/',
  CLIENT_PORTAL_PATROLS: '/client_portal/patrols',
  CLIENT_PORTAL_PATROL_LOGS: '/client_portal/patrol_logs',
  CLIENT_PORTAL_PATROL_VIEW: '/client_portal/patrol_view',
  CLIENT_PORTAL_REPORTS: '/client_portal/reports',
  CLIENT_PORTAL_REPORT_VIEW: '/client_portal/report_view',
  CLIENT_PORTAL_EMP_DAR_LIST: '/client_portal/emp_dar_list',
  CLIENT_PORTAL_EMP_DAR_VIEW: '/client_portal/emp_dar_view',
  CLIENT_PORTAL_SHIFTS: '/client_portal/shifts',
  CLIENT_PORTAL_SHIFT_VIEW: '/client_portal/shift_view',
  CLIENT_PORTAL_MESSAGING: '/client_portal/messaging',
  EMERGENCY_RESPONSE_LIST: '/emergency_response_list',

  CALL_OUT_LIST: '/callout_list',
  CALL_OUT_VIEW: '/callout_view',

  AUDIT_DASHBOARD: '/audit_dashboard',

  HRM_HOME: '/hrm_home',
  HRM_LEAVE_REQ_LIST: '/hrm_leave_request_list',

  //Unprotected page
  PRIVACY_POLICY: '/unprotected/privacy_policy',
  USER_DATA_DELETION_REQUEST: '/unprotected/user_data_deletion_request',
};

export const LocalStorageKey = {
  LOGGEDIN_USER: 'loggedInUser',
  SELECTED_BRANCH: 'selectedBranch',
  SELECTED_LOCATION: 'selectedLocation',
  FCM_TOKEN: 'fcm_token',
};

export enum IUserType {
  ADMIN = 'admin',
  SUPER_ADMIN = 'super_admin',
  CLIENT = 'client',
  EMPLOYEE = 'employee',
}

export interface LocalStorageLoggedInUserData {
  LoggedInId: string;
  LoggedInUserId: string;
  LoggedInCrypt: string;
  LoggedInAuthUserType: IUserType;
}

export enum ScheduleView {
  CALENDAR_VIEW = 'calendar_view',
  BY_EMPLOYEE_VIEW = 'by_employee_view',
  STATISTICS_VIEW = 'statistics_view',
}

export enum PerformanceSortType {
  OVERALL = 'overall',
  SHIFT = 'shift',
  PATROL = 'patrol',
  SHIFT_HRS = 'shift_hrs',
  DARS = 'dars',
  REPORTS = 'reports',
}
